services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: julio
      POSTGRES_PASSWORD: 5432
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: julioamsf@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 8081
    ports:
      - 8081:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db:
    driver: local
  pgadmin:
    driver: local